version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: tictactoang-mongo
    ports:
      - "27017:27017"
    volumes:
      - tictactoang-mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: tictactoang-redis
    ports:
      - "6379:6379"
    volumes:
      - tictactoang-redis-data:/data
    restart: unless-stopped

volumes:
  tictactoang-mongo-data:
  tictactoang-redis-data: